### ISSUE TITLE
Remove send image from cryptway send page

### ISSUE THREAD

**Issue by mr-raam** [cryptway/cryptway#2]
Remove send image from cryptway send page , that is hiding the below options
![image](https://user-images.githubusercontent.com/96066541/208970885-87052af9-59cd-4688-ac84-5d840e65921c.png)

**Comment by Ajinkgupta** [comment]
fixed in      latest commit

 [https://github.com/cryptway/cryptway/commit/7ac73b8298287d5106495ad35fddd856ea86be6f](fixed)
